server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/gadgets_store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

# Optionally adjust allowed origins in CorsConfig